services:
  - type: web
    name: solarops-backend
    runtime: node
    repo: https://github.com/yourusername/solarops
    branch: main
    rootDir: apps/backend
    buildCommand: cd ../.. && pnpm install --no-frozen-lockfile && cd apps/backend && pnpm db:generate && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: FRONTEND_URL
        value: https://solar-ops.vercel.app
      - key: OPENAI_API_KEY
        sync: false
      - key: NREL_API_KEY
        sync: false