export declare const US_STATES: {
    readonly AL: "Alabama";
    readonly AK: "Alaska";
    readonly AZ: "Arizona";
    readonly AR: "Arkansas";
    readonly CA: "California";
    readonly CO: "Colorado";
    readonly CT: "Connecticut";
    readonly DE: "Delaware";
    readonly FL: "Florida";
    readonly GA: "Georgia";
    readonly HI: "Hawaii";
    readonly ID: "Idaho";
    readonly IL: "Illinois";
    readonly IN: "Indiana";
    readonly IA: "Iowa";
    readonly KS: "Kansas";
    readonly KY: "Kentucky";
    readonly LA: "Louisiana";
    readonly ME: "Maine";
    readonly MD: "Maryland";
    readonly MA: "Massachusetts";
    readonly MI: "Michigan";
    readonly MN: "Minnesota";
    readonly MS: "Mississippi";
    readonly MO: "Missouri";
    readonly MT: "Montana";
    readonly NE: "Nebraska";
    readonly NV: "Nevada";
    readonly NH: "New Hampshire";
    readonly NJ: "New Jersey";
    readonly NM: "New Mexico";
    readonly NY: "New York";
    readonly NC: "North Carolina";
    readonly ND: "North Dakota";
    readonly OH: "Ohio";
    readonly OK: "Oklahoma";
    readonly OR: "Oregon";
    readonly PA: "Pennsylvania";
    readonly RI: "Rhode Island";
    readonly SC: "South Carolina";
    readonly SD: "South Dakota";
    readonly TN: "Tennessee";
    readonly TX: "Texas";
    readonly UT: "Utah";
    readonly VT: "Vermont";
    readonly VA: "Virginia";
    readonly WA: "Washington";
    readonly WV: "West Virginia";
    readonly WI: "Wisconsin";
    readonly WY: "Wyoming";
};
export declare const ROOF_TYPES: readonly ["Asphalt Shingle", "Metal", "Tile", "Flat/Membrane", "Wood Shake", "Slate", "Other"];
export declare const PROPERTY_TYPES: readonly ["Single Family Home", "Townhouse", "Condo", "Multi-Family", "Commercial", "Other"];
export declare const ELECTRICAL_PANEL_SIZES: readonly ["100 Amp", "125 Amp", "150 Amp", "200 Amp", "225 Amp", "400 Amp", "Other"];
export declare const AGENT_RETRY_CONFIG: {
    maxAttempts: number;
    backoffMultiplier: number;
    initialDelay: number;
    maxDelay: number;
};
export declare const QUEUE_NAMES: {
    readonly PERMIT_OFFICE: "permit-office-queue";
    readonly PARCEL_INFO: "parcel-info-queue";
    readonly OPEN_SOLAR: "open-solar-queue";
    readonly PROPOSAL: "proposal-queue";
};
//# sourceMappingURL=constants.d.ts.map